title: SunshineVaniCaramel by Lukasz Adam
author: Lukasz Adam

gem: "jekyll", "3.4.3"

include:
  - redirects
  - _redirects
  
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock