title: SunshineVaniCaramel by Lukasz Adam
author: Lukasz Adam




gems:
 - jekyll-sitemap

include:
  - redirects
  - _redirects
  
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock